### PR TITLE
React rewrite is here owo

### PR DESCRIPTION
**Pull request by cyyynthia**
It's time to use React! I've made some ""minor"" changes to the existing codebase lol

# Environment

I've used React + Redux and some other cool dependencies and I tried to keep code clean and optimized

For now, the server represents a serious bottleneck with inconsistent behaviour (see Login/index.tsx for ex), lack of documentation and weird behaviour with empty database (not handled properly)

It'll need an update/partial rewrite to be more easily updated and installed (It took me like 1h to figure out how to make it work properly, and spoiler alert: my local install is ugly af) with maybe database migration & better handling of clean installs

# Features

 - Optimized (can probably be more optimized, but I tried to cover most important stuff like useless renders etc)
 - Handles dynamically API config
 - Covers most of actual features
 - Invites URL
 - Crash handling with a fancy window https://cdn.bowser65.tk/s/fKIqvjmg.png (not used yet)
 - Designed to handle huge amount of data (not implemented, see todos)
 - Websocket logic separated from render logic thanks to Redux
 - Some debug in the console in production + Redux logs when in development

# Todos

 - Config some linters - I regularly use my IDE to reformat everything but it's not perfect, and my css is awful (I don't really care about property ordering xD)
 - More optimization: Server/Chat.tsx can be easily optimized I think
 - User avatars
 - Emojis (I was thinking about multiple emojis categories: Twemoji, Blobs, blobcats & custom emotes per server)
 - Websocket reconnect with exponential backoff
 - Use better stuff than `alert()` `confirm()` and `prompt()`
 - Handle major crashes with the fancy dialog (and report them to sentry?)
 - Prepare the app to handle lots of data (Cannot be done with current API endpoints, or partially)
 - Update Union-Server

### CODE REVIEW

**Comment by devoxin** [comment]
i don't touch react stuff but this looks hella good, nice work

**Comment by cyyynthia** [comment]
thanks :) Now i'm gonna work on the server (and maybe work on make voice stuff stable and working 👀)

**Comment by alula** [comment]
Whoa, you just did a lot of great work, but there's small problem: one of the dependencies aren't compatible with node.js 10.

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

**Review by alula — CHANGES_REQUESTED** [review]
fix node.js 10 compatibility

**Comment by cyyynthia** [comment]
I ran into the same problem on my local install (I use node 10) because upath is required by webpack
After a quick search the only solution was to disable engine compatibility check and everything works properly

**Review by alula — APPROVED** [review]

**Pull request merged**
